### ISSUE TITLE
Feature request: Add base-uri, form-action, and frame-ancestors policies

### ISSUE THREAD

**Issue by ccsaposs** [MarcelloTheArcane/netlify-plugin-csp-generator#2]
Hi,

Would it be possible to add support for the base-uri, form-action, and frame-ancestors policies?

I tried adding them in my `_headers` file, but it looks like the `Content-Security-Policy` header is being overridden by this plugin.

Also, I noticed that `upgrade-insecure-requests` is automatically added to the CSP.  Is it possible to disable this?

Thank you for your time.

**Comment by MarcelloTheArcane** [comment]
Wow, someone's using this!

Anyway...

I wasn't aware of these additional headers, I'll add them as soon as possible.  You probably can use them anyway, if you just add the name in camel case to your netlify.toml:

``` toml
  [plugins.inputs.policies]
    baseUri = "'self'"
    formAction = "'self'"
    frameAncestors = "'self'"
```

I haven't tried this, but I see no reason for it not to work.
